/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// Send is a function that uses SORACOM Arc configuration provided as a JSON string,
// an HTTP method, a path, and a payload to create and execute an HTTP request to the SORACOM Unified Endpoint.
// The function returns the response as a C language string, or nil if an error occurs.
// Input parameters are expected to be C language strings.
//
// Parameters:
//   - `configJson`: C string representation of SORACOM Arc configuration
//   - `method`: HTTP method to be used in the request. Only GET and POST are supported.
//   - `path`: path to be used in the HTTP request
//   - `body`: body of the HTTP request
//
// Returns:
//   - C string representation of the HTTP response body, or nil if an error occurred
//
// Usage:
//
//	response := Send(configJson, method, path, body)
//
extern char* Send(char* configJson, char* method, char* path, char* body);

// SendUDP is a function that uses SORACOM Arc configuration provided as a JSON string,
// a port, and a payload to create and execute an UDP request to the SORACOM Unified Endpoint.
// The function returns the response as a C language string, or nil if an error occurs.
// Input parameters are expected to be C language strings.
//
// Parameters:
//   - `configJson`: C string representation of SORACOM Arc configuration
//   - `body`: body of the UDP request
//   - `bodyLen`: length of the body
//
// Returns:
//   - C string representation of the UDP response body, or nil if an error occurred
//
// Usage:
//
//	response := SendUDP(configJson, body, bodyLen)
//
extern char* SendUDP(char* configJson, char* body, int bodyLen, int port, int timeout);

#ifdef __cplusplus
}
#endif
